export const navLinks = [
  { title: "Home", href: "/", src: "/images/nav_images/home.webp" },
  {
    title: "Music",
    href: "/music",
    src: "/images/nav_images/music.webp",
  },
  {
    title: "Reviews",
    href: "/music-reviews",
    src: "/images/nav_images/music-reviews.webp",
  },
  {
    title: "Shoots",
    href: "/shoots",
    src: "/images/nav_images/shoots.webp",
  },
  {
    title: "Poems",
    href: "/poems",
    src: "/images/nav_images/poems.webp",
  },
  {
    title: "Contact",
    href: "/contact",
    src: "/images/nav_images/contact.webp",
  },
];

export const aboutData = [
  "Șèyí,ThePoet is a passionate spoken word artist, model and creative director; who brings raw emotion and profound insight to the stage. His performances, rich with themes of mental health and the human experience, have touched hearts and sparked conversations. Notable highlights of his career include a moving performance at the SFU Black Caucus Graduation, winning second place at the highly regarded Da Luv Jones Slam Competition being featured in Vogue Mexico and Pakistan, GMARO magazine and creative directing ‘STACKED’ -  a new sustainable fashion runway in Vancouver, BC.",
  "Balancing his artistic pursuits with academic endeavors, Șèyí,ThePoet is studying Music and honing his technical skills as an Audio Tech intern at Lobe Studios - the first dedicated spatial sound studio in North America to work with a permanently integrated 4DSOUND system. This combination of creativity and technical expertise allows him to craft performances that are both emotionally powerful and sonically refined. Șèyí,ThePoet is also a proud Grammy U Member of the LA Chapter.",
  "Șèyí,ThePoet uses his art to explore and document the struggles and triumphs of everyday life, offering a voice to those who may feel unheard. His work resonates deeply with audiences, creating connections and fostering a greater understanding of the shared human experience. Whether on stage, set or in the studio, Șèyí,ThePoet is dedicated to making a meaningful impact through his words, actions and music.",
];

export const recentsData = [
  {
    id: 1,
    title: "PERFORMANCE AT TALK WITH SOSA: A MENTAL HEALTH CONFERENCE",
    text: "Performing for this event meant a lot to me as i have also struggled  with mental health issues in the past. I was extremly honoured to play  my piece “I love you,” a tale of two lovers in a toxic cylce, “if my  bottle could talk”, a poem about alcholism, “lost”, a poem about the  troubles finiding yourself in a new enovironment as an international  student.",
    images: [
      "/images/recent_images/performance_talk_with_sosa_1.webp",
      "/images/recent_images/performance_talk_with_sosa_2.webp",
      "/images/recent_images/performance_talk_with_sosa_3.webp",
      "/images/recent_images/performance_talk_with_sosa_4.webp",
    ],
  },
  {
    id: 2,
    title: "Sèyí Synth 5k",
    text: "Synth made with Max MSP",
    images: ["/images/recent_images/synth.webp"],
  },
  {
    id: 3,
    title: "UPCOMING ALBUM: OLUWASEYI, THE PROTAGONIST",
    text: "",
    images: [
      "/images/recent_images/album_1.webp",
      "/images/recent_images/album_2.webp",
      "/images/recent_images/album_3.webp",
      "/images/recent_images/album_4.webp",
    ],
  },
];

export const musicImages = [
  { src: "/images/music_images/fwut-1.webp" },
  { src: "/images/music_images/fwut-2.webp" },
  { src: "/images/music_images/fwut-3.webp" },
  { src: "/images/music_images/fwut-4.webp" },
  { src: "/images/music_images/fwut-5.webp" },
];

export const reviews = [
  {
    id: 1,
    album_name: "Heis",
    artist: "Rema",
    released: "2024",
    details: [
      {
        src: "/images/review_images/review-1.webp",
        p1: "Rema has returned with an album that not only cements his place at the top of the new wave of Afrobeats artists but also showcases his unique artistry and bold creativity. From the outset, Rema’s mission is to demonstrate his dominance and versatility within the genre.",
        p2: "The album kicks off with an intensity that is hard to ignore. Rema bursts out of the gates with the energy of a sprinter, setting a pace that is relentless, only easing up near the very end. His choice of beats is as polarizing as it is innovative, with tracks that weave between ethereal vocal deliveries and sharply crafted songwriting. Rema doesn’t just want to be heard—he demands it, asserting his presence as if to say, “I am HIM.” The confidence is palpable and unapologetic.",
        p3: "On the track 'Hehehehe,', Rema repeats with conviction that he 'isn’t going to take it on his hater,' a statement that feels both like a mantra and a warning. Following this, 'Yayo' showcases Rema’s vocal agility and his ability to find unique rhythmic pockets within the music. Here, he boasts of his success—money, hits, women, and cars—delivering each line with a flair that’s almost theatrical.",
        p4: "This album is bold, and it dares to be different. There’s a certain Yeezus-like vibe in its unapologetic nature, a raw authenticity that makes it feel almost outrageous in its self-assurance. Rema’s confidence in his art is admirable, and it’s clear that Mavin Records has given him the creative freedom to explore and push boundaries. This level of artistic control is rare, especially for artists on the rise, and it’s something that has allowed Rema to produce a body of work that is as defining for his career as it is for the current state of Afrobeats.",
        p5: "The timing of this album is crucial. Afrobeats has reached a crossroads, where the soundscape is increasingly dominated by more watered-down iterations of the genre. Rema’s album feels like a necessary disruption, following in the footsteps of groundbreaking albums like 'Made In Lagos' (MMWTV) and 'Superstar'. It’s a reminder of what Afrobeats can be when artists are allowed to experiment and stay true to their roots.",
        p6: "If there’s one critique, it’s the album’s relentless pace. The high BPM and non-stop energy can be overwhelming, with the only reprieve coming in the form of the final two tracks. However, even this ties into the overall concept, creating a listening experience that is as exhausting as it is exhilarating.",
        p7: "In the end, this album isn’t just a collection of songs—it’s a statement. It’s Rema proving a point, and doing so with a style and bravado that is uniquely his.",
        conclusion: "So, to wrap it up: “Siri, play me OZEBA jaare.”",
      },
    ],
  },
  {
    id: 2,
    album_name: "Lungu Boy",
    artist: "Asake",
    released: "2024",
    details: [
      {
        src: "/images/review_images/review-2.webp",
        p1: "Lungu Boy to Space: A Poetry Album Review on Lungu Boys.",
        p2: "On Asake’s second work of art, We take a dive into the mind of the lungu boy himself, Swimming through his mother’s words on patience, backstroking through his struggles in his early stage of his career and belly flopping into his love for skating.",
        p3: "Asake doesn’t fail to take the listener on a serious aquatic lesson. Some essentials include life jacket synthesizers and live “swimsuit” instrumentals.",
        p4: "Can’t help but mention life guards Sarz and Pprime Ensuring our safety as we breaststroke through the famous “my heart”, the notorious sea called “wave” and the breath taking ocean “worldwide” Oh my! Their production could sink the titanic !",
        p5: "During my lesson central cee instilled in me the dangers of riding a wave alone at sea Stormzy seems to be alright with it, his only advice to me was to be patient.",
        p6: "LUDMILLA, whines about the sharks notorious essence.",
        p7: "The class ends with a delicacy We had the bass and choir entry at the 18 second mark on “Worldwide” The maxing guitar intro on “My heart” And the ethereal synth on “Wave”",
        conclusion: "A delicious feast to say the least 8/10",
      },
    ],
  },
];

export const shootImages = [
  {
    id: 1,
    link_title: "/shoots/shoot1-vfw-23-blue-tamburin",
    src: "/images/shoot_images/1.webp",
    title: "VFW SS'23 - BLUE TAMBURIN",
    color: "#74D3AE",
  },
  {
    id: 2,
    link_title: "/shoots/shoot2-vfw-23-blue-tamburin",
    src: "/images/shoot_images/2.webp",
    title: "VFW SS'23 - BLUE TAMBURIN",
    color: "#07D9A8",
  },
  {
    id: 3,
    link_title: "/shoots/shoot3-vfw-23-backstage",
    src: "/images/shoot_images/3.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#E03838",
  },
  {
    id: 4,
    link_title: "/shoots/shoot4-vfw-23-backstage",
    src: "/images/shoot_images/4.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#E03838",
  },
  {
    id: 5,
    link_title: "/shoots/shoot5-vfw-23-backstage",
    src: "/images/shoot_images/5.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#5F6332",
  },
  {
    id: 6,
    link_title: "/shoots/shoot6-vfw-23-seyi-and-milo",
    src: "/images/shoot_images/6.webp",
    title: "VFW SS'23 - SÈYÌ AND MILO MANHEIM",
    color: "#5F6332",
  },
  {
    id: 7,
    link_title: "/shoots/shoot7-vfw-23-backstage",
    src: "/images/shoot_images/7.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#5F6332",
  },
  {
    id: 8,
    link_title: "/shoots/shoot8-vfw-23-backstage",
    src: "/images/shoot_images/8.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#D411AA",
  },
  {
    id: 9,
    link_title: "/shoots/shoot9-vfw-23-backstage",
    src: "/images/shoot_images/9.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#D411AA",
  },
  {
    id: 10,
    link_title: "/shoots/shoot10-vfw-23-unserten",
    src: "/images/shoot_images/10.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 11,
    link_title: "/shoots/shoot11-vfw-23-unserten",
    src: "/images/shoot_images/11.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 12,
    link_title: "/shoots/shoot12-vfw-23-unserten",
    src: "/images/shoot_images/12.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#9B9B9B",
  },
  {
    id: 13,
    link_title: "/shoots/shoot13-vfw-23-unserten",
    src: "/images/shoot_images/13.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 14,
    link_title: "/shoots/shoot14-vfw-23-unserten",
    src: "/images/shoot_images/14.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 15,
    link_title: "/shoots/shoot15-vfw-23-unserten",
    src: "/images/shoot_images/15.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 16,
    link_title: "/shoots/shoot16-vfw-22-toot",
    src: "/images/shoot_images/16.webp",
    title: "VFW SS'22 - TOOT",
    color: "#D91B1B",
  },
  {
    id: 17,
    link_title: "/shoots/shoot17-vfw-22-alteir-coin",
    src: "/images/shoot_images/17.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#D91B1B",
  },
  {
    id: 18,
    link_title: "/shoots/shoot18-vfw-22-alteir-coin",
    src: "/images/shoot_images/18.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#D91B1B",
  },
  {
    id: 19,
    link_title: "/shoots/shoot19-vfw-22-alteir-coin",
    src: "/images/shoot_images/19.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#7D0606",
  },
  {
    id: 20,
    link_title: "/shoots/shoot20-vfw-22-alteir-coin",
    src: "/images/shoot_images/20.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#7D0606",
  },
  {
    id: 21,
    link_title: "/shoots/shoot21-vfw-22-alteir-coin",
    src: "/images/shoot_images/21.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#7D0606",
  },
  {
    id: 22,
    link_title: "/shoots/shoot22-2022-ike-photoshoot",
    src: "/images/shoot_images/22.webp",
    title: "PHOTO SHOOT WITH IKE 2022",
    color: "#17C128",
  },
  {
    id: 23,
    link_title: "/shoots/shoot23-2022-ike-photoshoot",
    src: "/images/shoot_images/23.webp",
    title: "PHOTO SHOOT WITH IKE 2022",
    color: "#17C128",
  },
  {
    id: 24,
    link_title: "/shoots/shoot24-2022-portfolio",
    src: "/images/shoot_images/24.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#7E867E",
  },
  {
    id: 25,
    link_title: "/shoots/shoot25-2022-portfolio",
    src: "/images/shoot_images/25.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#7E867E",
  },
  {
    id: 26,
    link_title: "/shoots/shoot26-2022-portfolio",
    src: "/images/shoot_images/26.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#948250",
  },
  {
    id: 27,
    link_title: "/shoots/shoot27-2022-portfolio",
    src: "/images/shoot_images/27.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#948250",
  },
  {
    id: 28,
    link_title: "/shoots/shoot28-2022-portfolio",
    src: "/images/shoot_images/28.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#948250",
  },
];

export const poems = [
  {
    id: 1,
    title: "Untitled 1",
    lines: [
      "/*",
      "I hope the things I said out of ignorance are forgiven. ",
      "What does a shielded child know? We don't do shit like this back at home, so IDK, IDK.",
      "Correct me if I'm wrong.",
      "Don't be throwing stones.",
      "IDK, IDK.",
      "Please lower your tone.",
      "IDK, IDK…",
      "*/",
    ],
  },
  {
    id: 2,
    title: "Untitled 2",
    lines: [
      "/*",
      "I forgive my mother for the hurtful things she said to me whilst growing up.",
      "I forgive my father for walking out the door when I needed him the most.",
      "I forgive myself for saying some hurtful things I didn't mean.",
      "I forgive myself for walking out of doors that meant something to me.",
      "I learned to grow as a man, even with broken foundations.",
      "I understood too much whilst growing up; now the anger has taken a toll.",
      "I have to learn to let some things go.",
      "I understood what love was and ran home to safety.",
      "And if love leads me to hurt, I don't wanna go.",
      "I have seen things I don't wanna see…",
      "*/",
    ],
  },
  {
    id: 3,
    title: "Untitled 3",
    text: "I understand where they were coming from Maybe I forgave to easily cause the anger still boils in my bones I had to let some things go",
    lines: [
      "/*",
      "I understand where they were coming from",
      "Maybe I forgave to easily cause the anger still boils in my bones ",
      "I had to let some things go ",
      "*/",
    ],
  },

  {
    id: 4,
    title: "Untitled 4",
    text: "And I can never be perfect. I wonder why I try. I'm done trying to prove myself to you, It's exhausting. There's something liberating about accepting me for me. So today is about the death of the me that cared, that succumbed, the one that said 'sorry' multiple times or laughed when I didn't understand what you said, ''Young man please repeat yourself.'' And people tell me they love me; I couldn't believe it because I didn't love parts of myself. But this album is acceptance. And I thought my demons still lay with my innocence, but tonight they are all gone.",
    lines: [
      "/*",
      "And I can never be perfect.",
      "I wonder why I try. I'm done trying to prove myself to you,",
      "It's exhausting.",
      "There's something liberating about accepting me for me.",
      "So today is about the death of the me that cared, that succumbed,",
      "the one that said 'sorry' multiple times or laughed when I didn't understand what",
      "you said,",
      "“Young man please repeat yourself.”",
      "And people tell me they love me; I couldn't believe it because I didn't love parts of myself.",
      "But this album is acceptance. And I thought my demons still lay with my innocence, but tonight they are all gone.",
      "*/",
    ],
  },
  {
    id: 5,
    title: "Untitled 5",
    lines: [
      "/*",
      "I saw you with him just behind the pulpit.",
      "The air was thick with incense and secrets.",
      "You told him, “Be quiet, not a sound should leave your mouth.”",
      "Pushed him to his knees, unzipped your pants, and did your deed.",
      "Indeed, his sins were forgiven.",
      "Was that the communion you promised after the service,",
      "The same service where you preached about perversion?",
      "I'm throwing stones at the church house.",
      "She came to you battered and bruised,",
      "A millionaire had just taken advantage of her.",
      "“Preacher, preacher, please save me,”",
      "Bleeding from her inner thighs, bloodshot eyes,",
      "Broken heels, gum in her hair, torn pleated skirt.",
      "“Preacher man, preacher man, please save me.”",
      "You carried her to the pulpit,",
      "She told her story, raw and unfiltered,",
      "Every toss, turn, and mingling of fluids.",
      "The more she spoke, the slower you swallowed,",
      "Lust in your eyes, something else in your thighs.",
      "Right in front of the cross,",
      "You forcefully took a piece of the pie.",
      "“Preacher man, preacher man, don't.”",
      "I guess I'm throwing stones at the church house.",
      "And before my very eyes, the place I call home has been contaminated,",
      "Filled with lust and lies.",
      "Mr. Preacher man, who exactly are you preaching to?",
      "Does a few bad eggs make the whole basket bad?",
      "Can it?",
      "Who was I even looking up to?",
      "The farther I ran from God, the closer I got.",
      "I guess I'm throwing stones at the church house.",
      "*/",
    ],
  },
];
