export const aboutData = [
  "Șèyí,ThePoet is a passionate spoken word artist, model and creative director; who brings raw emotion and profound insight to the stage. His performances, rich with themes of mental health and the human experience, have touched hearts and sparked conversations. Notable highlights of his career include a moving performance at the SFU Black Caucus Graduation, winning second place at the highly regarded Da Luv Jones Slam Competition being featured in Vogue Mexico and Pakistan, GMARO magazine and creative directing ‘STACKED’ -  a new sustainable fashion runway in Vancouver, BC.",
  "Balancing his artistic pursuits with academic endeavors, Șèyí,ThePoet is studying Music and honing his technical skills as an Audio Tech intern at Lobe Studios - the first dedicated spatial sound studio in North America to work with a permanently integrated 4DSOUND system. This combination of creativity and technical expertise allows him to craft performances that are both emotionally powerful and sonically refined. Șèyí,ThePoet is also a proud Grammy U Member of the LA Chapter.",
  "Șèyí,ThePoet uses his art to explore and document the struggles and triumphs of everyday life, offering a voice to those who may feel unheard. His work resonates deeply with audiences, creating connections and fostering a greater understanding of the shared human experience. Whether on stage, set or in the studio, Șèyí,ThePoet is dedicated to making a meaningful impact through his words, actions and music.",
];

export const recentsData = [
  {
    id: 1,
    title: "PERFORMANCE AT TALK WITH SOSA: A MENTAL HEALTH CONFERENCE",
    text: "Performing for this event meant a lot to me as i have also struggled  with mental health issues in the past. I was extremly honoured to play  my piece “I love you,” a tale of two lovers in a toxic cylce, “if my  bottle could talk”, a poem about alcholism, “lost”, a poem about the  troubles finiding yourself in a new enovironment as an international  student.",
    images: [
      "/images/recent_images/performance_talk_with_sosa_1.webp",
      "/images/recent_images/performance_talk_with_sosa_2.webp",
      "/images/recent_images/performance_talk_with_sosa_3.webp",
      "/images/recent_images/performance_talk_with_sosa_4.webp",
    ],
  },
  {
    id: 2,
    title: "Sèyí Synth 5k",
    text: "Synth made with Max MSP",
    images: ["/images/recent_images/synth.webp"],
  },
  {
    id: 3,
    title: "UPCOMING ALBUM: OLUWASEYI, THE PROTAGONIST",
    text: "",
    images: [
      "/images/recent_images/album_1.webp",
      "/images/recent_images/album_2.webp",
      "/images/recent_images/album_3.webp",
      "/images/recent_images/album_4.webp",
    ],
  },
];

export const musicImages = [
  { src: "/images/music_images/fwut-1.webp" },
  { src: "/images/music_images/fwut-2.webp" },
  { src: "/images/music_images/fwut-3.webp" },
  { src: "/images/music_images/fwut-4.webp" },
  { src: "/images/music_images/fwut-5.webp" },
];

export const reviews = [
  {
    id: 1,
    album_name: "Heis.",
    artist: "Rema",
    released: "2024",
    details: [
      {
        src: "/images/review_images/review-1.webp",
        p1: "Rema has returned with an album that not only cements his place at the top of the new wave of Afrobeats artists but also showcases his unique artistry and bold creativity. From the outset, Rema’s mission is to demonstrate his dominance and versatility within the genre.",
        p2: "The album kicks off with an intensity that is hard to ignore. Rema bursts out of the gates with the energy of a sprinter, setting a pace that is relentless, only easing up near the very end. His choice of beats is as polarizing as it is innovative, with tracks that weave between ethereal vocal deliveries and sharply crafted songwriting. Rema doesn’t just want to be heard—he demands it, asserting his presence as if to say, “I am HIM.” The confidence is palpable and unapologetic.",
        p3: "On the track 'Hehehehe,', Rema repeats with conviction that he 'isn’t going to take it on his hater,' a statement that feels both like a mantra and a warning. Following this, 'Yayo' showcases Rema’s vocal agility and his ability to find unique rhythmic pockets within the music. Here, he boasts of his success—money, hits, women, and cars—delivering each line with a flair that’s almost theatrical.",
        p4: "This album is bold, and it dares to be different. There’s a certain Yeezus-like vibe in its unapologetic nature, a raw authenticity that makes it feel almost outrageous in its self-assurance. Rema’s confidence in his art is admirable, and it’s clear that Mavin Records has given him the creative freedom to explore and push boundaries. This level of artistic control is rare, especially for artists on the rise, and it’s something that has allowed Rema to produce a body of work that is as defining for his career as it is for the current state of Afrobeats.",
        p5: "The timing of this album is crucial. Afrobeats has reached a crossroads, where the soundscape is increasingly dominated by more watered-down iterations of the genre. Rema’s album feels like a necessary disruption, following in the footsteps of groundbreaking albums like 'Made In Lagos' (MMWTV) and 'Superstar'. It’s a reminder of what Afrobeats can be when artists are allowed to experiment and stay true to their roots.",
        p6: "If there’s one critique, it’s the album’s relentless pace. The high BPM and non-stop energy can be overwhelming, with the only reprieve coming in the form of the final two tracks. However, even this ties into the overall concept, creating a listening experience that is as exhausting as it is exhilarating.",
        p7: "In the end, this album isn’t just a collection of songs—it’s a statement. It’s Rema proving a point, and doing so with a style and bravado that is uniquely his.",
        conclusion: "So, to wrap it up: “Siri, play me OZEBA jaare.”",
      },
    ],
  },
];

export const shootImages = [
  {
    id: 1,
    link_title: "/shoots/shoot1-vfw-23-blue-tamburin",
    src: "/images/shoot_images/1.webp",
    title: "VFW SS'23 - BLUE TAMBURIN",
    color: "#74D3AE",
  },
  {
    id: 2,
    link_title: "/shoots/shoot2-vfw-23-blue-tamburin",
    src: "/images/shoot_images/2.webp",
    title: "VFW SS'23 - BLUE TAMBURIN",
    color: "#00FFC5",
  },
  {
    id: 3,
    link_title: "/shoots/shoot3-vfw-23-backstage",
    src: "/images/shoot_images/3.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#E03838",
  },
  {
    id: 4,
    link_title: "/shoots/shoot4-vfw-23-backstage",
    src: "/images/shoot_images/4.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#E03838",
  },
  {
    id: 5,
    link_title: "/shoots/shoot5-vfw-23-backstage",
    src: "/images/shoot_images/5.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#5F6332",
  },
  {
    id: 6,
    link_title: "/shoots/shoot6-vfw-23-seyi-and-milo",
    src: "/images/shoot_images/6.webp",
    title: "VFW SS'23 - SÈYÌ AND MILO MANHEIM",
    color: "#5F6332",
  },
  {
    id: 7,
    link_title: "/shoots/shoot7-vfw-23-backstage",
    src: "/images/shoot_images/7.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#5F6332",
  },
  {
    id: 8,
    link_title: "/shoots/shoot8-vfw-23-backstage",
    src: "/images/shoot_images/8.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#D411AA",
  },
  {
    id: 9,
    link_title: "/shoots/shoot9-vfw-23-backstage",
    src: "/images/shoot_images/9.webp",
    title: "VFW SS'23 - BACKSTAGE",
    color: "#D411AA",
  },
  {
    id: 10,
    link_title: "/shoots/shoot10-vfw-23-unserten",
    src: "/images/shoot_images/10.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 11,
    link_title: "/shoots/shoot11-vfw-23-unserten",
    src: "/images/shoot_images/11.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 12,
    link_title: "/shoots/shoot12-vfw-23-unserten",
    src: "/images/shoot_images/12.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#9B9B9B",
  },
  {
    id: 13,
    link_title: "/shoots/shoot13-vfw-23-unserten",
    src: "/images/shoot_images/13.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 14,
    link_title: "/shoots/shoot14-vfw-23-unserten",
    src: "/images/shoot_images/14.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 15,
    link_title: "/shoots/shoot15-vfw-23-unserten",
    src: "/images/shoot_images/15.webp",
    title: "VFW SS'23 - UNSERTEN",
    color: "#4E0505",
  },
  {
    id: 16,
    link_title: "/shoots/shoot16-vfw-22-toot",
    src: "/images/shoot_images/16.webp",
    title: "VFW SS'22 - TOOT",
    color: "#D91B1B",
  },
  {
    id: 17,
    link_title: "/shoots/shoot17-vfw-22-alteir-coin",
    src: "/images/shoot_images/17.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#D91B1B",
  },
  {
    id: 18,
    link_title: "/shoots/shoot18-vfw-22-alteir-coin",
    src: "/images/shoot_images/18.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#D91B1B",
  },
  {
    id: 19,
    link_title: "/shoots/shoot19-vfw-22-alteir-coin",
    src: "/images/shoot_images/19.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#7D0606",
  },
  {
    id: 20,
    link_title: "/shoots/shoot20-vfw-22-alteir-coin",
    src: "/images/shoot_images/20.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#7D0606",
  },
  {
    id: 21,
    link_title: "/shoots/shoot21-vfw-22-alteir-coin",
    src: "/images/shoot_images/21.webp",
    title: "VFW SS'22 - ALTEIR COIN",
    color: "#7D0606",
  },
  {
    id: 22,
    link_title: "/shoots/shoot22-2022-ike-photoshoot",
    src: "/images/shoot_images/22.webp",
    title: "PHOTO SHOOT WITH IKE 2022",
    color: "#17C128",
  },
  {
    id: 23,
    link_title: "/shoots/shoot23-2022-ike-photoshoot",
    src: "/images/shoot_images/23.webp",
    title: "PHOTO SHOOT WITH IKE 2022",
    color: "#17C128",
  },
  {
    id: 24,
    link_title: "/shoots/shoot24-2022-portfolio",
    src: "/images/shoot_images/24.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#7E867E",
  },
  {
    id: 25,
    link_title: "/shoots/shoot25-2022-portfolio",
    src: "/images/shoot_images/25.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#7E867E",
  },
  {
    id: 26,
    link_title: "/shoots/shoot26-2022-portfolio",
    src: "/images/shoot_images/26.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#948250",
  },
  {
    id: 27,
    link_title: "/shoots/shoot27-2022-portfolio",
    src: "/images/shoot_images/27.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#948250",
  },
  {
    id: 28,
    link_title: "/shoots/shoot28-2022-portfolio",
    src: "/images/shoot_images/28.webp",
    title: "PORTFOLIO SHOOT 2022",
    color: "#948250",
  },
];
